language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: p4nOicCFK7Mb2CmTP1W55WO7FuB/EJ9uTDYIkFD9B07vixwzhLz7VjPQDf4OdCOUtEzbmJ4FM8+/0VHZcRUL4/Dg6sNGdxBCoYyFv/VdEecxKgmsIJFwQLH3DiYxYwOyhxf41tiBpG4ZuJGg/sxFxElKO7udHCpgKM8VsJ7+eudkCbgs1ClPRfLS5q+BcgtO5rmFOL32bMNA1/7zUnmntBNtfGsGShgz5CML9NGYdGiiIoMIgzpMDIOI3f92S0tXxHtXvCSlXw4KfMUgEFAu79d/XoVLDvF6Uhj5QxfckvsamtiQT0PS61ec3s3rO/DHyRsFwAwVF9tWClp/HXbrT0dx8WQ8lLUjVYzxKj51hVbL7cs8WVyufLkCV6w2wpzWAxYF6H6WfsL1ptRsQ7QLbggPy093e04RsABYXaD+mQD9adWsszm9UOpqGOA2oOapZatCf4GMnvKxc17np4XEZ8wAIepHOxneCvQmx6URfWbpNDTzwRf27+dkmr1d1Hhba1sPBXTkb8cNIQkduwKA+UanMSrCDKJWJJimqQzl4qNwURm1HWDLQzO4RPISN/0JBv327Sjf3aqAjKlaiJvkYMZsyRTjO0iXRSh+bWvO9sxP8nck1ei6mdLLEu3AfC6Oh3ku0dwdEpf0Rox6rqHTm7vXmM2+LJMBpV7iaB5OFKk=
  file:
    - 'unist-util-modify-children.js'
    - 'unist-util-modify-children.min.js'
  on:
    tags: true
